spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gerenciador_funcionarios
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
